---
# GitHub username or organization and repo name
repo: dandeangelis/datilupo

# Email address and user name that you want to associate with the automated deploys
# Generally you want these to be different from your user account so it is clear
# which commits are automated.
deploy_email: "danieledeangelis1988@gmail.com"
deploy_username: "Daniele Bot"
---
